use_frameworks!

platform :ios, '8.0'

target 'WeexIosPgyUpdate_Example' do
  pod 'WeexIosPgyUpdate', :path => '../'

  target 'WeexIosPgyUpdate_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
